### ISSUE TITLE
Consider replacing org.instaslice/<uid> resources with node selectors

### ISSUE THREAD

**Issue by tardieu** [openshift/instaslice-operator#101]
InstaSlice needs a mechanism to constrain the scheduler to schedule a pod on the node chosen by InstaSlice for this pod. Currently this is achieved by injecting in the pod spec via webhook a resource request for a unique fake synthetic resource in the format `org.instaslice/<uid>`. InstaSlice then dynamically adds this synthetic resource to the targeted node capacity once it has made its decision.

Kubernetes permits adding node selectors to gated pods. See for instance here: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/#mutable-pod-scheduling-directives.

Instead of fake resources, we could therefore rely on node selectors to force node selection, alleviating the need for directly mutating the node capacity. The key benefits are:
- Replace a stateful mechanism with a stateless mechanism. In particular, we have observed situations where `org.instaslice/<uid>` resources are not collected as expected. This state also complicates the restart logic.
- Replace an asynchronous, high-latency mechanism with a zero-delay mechanism. 

This would probably require having the daemonset label the nodes at boot time to support single-node selectors.

We could also consider node affinity as an alternative to node selector, but the more general affinity mechanism does not seem required here.

**Comment by tardieu** [comment]
Node selectors with static labels are less flexible than `org.instaslice/<uid>` resources, because we can control the creation and deletion of these resources. In particular, a pod cannot be scheduled before the resource is created. We may have to label nodes dynamically to achieve the same. However, scheduling gates should be enough to delay the scheduling of a pod, so it should be possible to use static labels. We need to look into this carefully.

One reason to drop `org.instaslice/<uid>` is for scalability reasons as we may end up with 8x7=56 such resources for node in the cluster. In contrast, labels are per node so less of a scalability issue even if we have to create them dynamically.

**Comment by asm582** [comment]
Solved by #141
