### ISSUE TITLE
Support podman for running the demo on Kind

### ISSUE THREAD

**Issue by empovit** [openshift/instaslice-operator#14]
* Make the Kind provider configurable
* Update scripts and Makefiles
* Update the README

**Comment by empovit** [comment]
Podman is already supported for building images, but not for running Kind. Is supporting Podman with Kind (which is an experimental feature) worth the effort, or should we focus on deploying on K8s/OpenShift, and let those on Kind use Docker?

**Comment by asm582** [comment]
For now, I vote on letting users on KinD use Docker

**Comment by kannon92** [comment]
The main issue I have with letting users use Docker is that as openshift engineers we don't have a representative environment for development.

We don't support containerd in openshift so it may make it difficult to test openshift container runtime issues. Also if we ever get a feature into CRI-O before containerd it makes testing very difficult.

**Comment by empovit** [comment]
I think if the intention is to make it run on OpenShift, it should be developed as such.  Maybe OpenShift Local (aka CRC). The question is not whether Kind can run on Podman, but if we want to direct the development efforts elsewhere (e.g. OpenShift).

**Comment by kannon92** [comment]
I guess I am more familiar with doing development ahead of openshift releases. ie k8s or crio development where we don't have an openshift cluster to work on. So that is where I was coming from.

I think since this operator is not using any CRIO/K8s feature it would be fine to assume that you can get an openshift cluster to install this operator on.

**Comment by empovit** [comment]
As we can't seem to come to any conclusion, maybe it would be best to defer this decision for later. I'll leave this issue open for now.

**Comment by empovit** [comment]
The NVIDIA Container Toolkit (CTK) doesn't support Podman runtime. With Podman, it uses Container Device Interface (CDI), but InstaSlice can't work with CDI therefore we can't currently support Podman with Kind. I'm closing this issue. For development, Kind+Docker or OpenShift Local (CRC) can be used.
