### ISSUE TITLE
 Allocations present in deleted state post pod deletes

### ISSUE THREAD

**Issue by asm582** [openshift/instaslice-operator#150]
This is not harmful for pod allocations as deleted allocations are reused in the system, when hundreds of pods are deleted we usually see dangling 1 or 2 allocations in the deleted state. This could be the issue with the stale InstaSlice object which needs further investigation. if hundreds of pods are resubmitted the InstaSlice object gets in sync due to churn in the system.  Refer this comment: https://github.com/openshift/instaslice-operator/pull/141#discussion_r1792333220

**Comment by asm582** [comment]
PR #184 has addressed this issue and local testing for me shows the same

**Comment by kannon92** [comment]
/close

#184 seems to mean that this is complete.
