### ISSUE TITLE
controller pods will not start due to security policy issues

### ISSUE THREAD

**Issue by cpmeadors** [openshift/instaslice-operator#213]
This is the error in the Events of the ReplicaSet for the controller deployment:

Error creating: pods "instaslice-operator-controller-manager-586f8db77c-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .containers[0].allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed, provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount, no access to scc/restricted: Forbidden: the pod fails to validate against the `restricted-v2` security context constraint, but would validate successfully against the `restricted` security context constraint]

To reproduce:
Deploy openshift cluster (I am using 4.17 via clusterbot) 

$ oc new-project instaslice-system

$ operator-sdk run bundle quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-operator-bundle@sha256:e6d7b63c4de35ad1d779dada196c37e740e031a9dfa735b4708b13f56eb21761 --namespace instaslice-system

The bundle was build by konflux for https://github.com/openshift/instaslice-operator/pull/200 which is adding all the openshift specific build configuration needed for releases through konflux.

**Comment by harche** [comment]
@cpmeadors you need to use `make ocp-deploy-emulated`

**Comment by cpmeadors** [comment]
I was using "operator-sdk run bundle" because it similuates deploying through operatorhub.  When I modified the securityContexts fields to be in line with a non-privileged pod, then the controller was able to start.

**Comment by kannon92** [comment]
/close

Assuming #200 solved this.
