### ISSUE TITLE
Instaslice interaction with workloads

### ISSUE THREAD

**Issue by kannon92** [openshift/instaslice-operator#24]
I am curious how much testing has been done with Instaslice and workloads (Deployments/StatefulSets/Jobs/PyTorch/etc).

All the examples use Pods but in production one would expect to use a deployment or statefulset (for serving) and Jobs/PyTorchJob/CronJob for batch related tasks.

We should test how the gating would work on these objects and add some samples to show that this is ready for production usage.

**Comment by asm582** [comment]
Thanks for creating this issue, opened a draft PR here: #28

**Comment by asm582** [comment]
@kannon92 FYI, we now have samples for "core" kind types, please feel free to add other workload samples and share a PR

**Comment by kannon92** [comment]
I think we can close this.

/close
