### ISSUE TITLE
Pending items for the DP Release

### ISSUE THREAD

**Issue by harche** [openshift/instaslice-operator#303]
- [ ] CI jobs that runs e2e tests in emulated mode in konflux 
- [ ] Convert existing daemonset tests in bash script to either golang ginkgo e2e or bats tests.
- [ ] Daemonset tests must also be able to run on OCP 
- [ ] Refactor existing e2e tests to use golang controller runtime client instead of executing `kubectl` binary
- [ ] Create documentation for installing instaslice in both emulated and non-emulated mode on OCP (which can be referenced in OCP released notes). The documentation for non-emulated mode should also point towards installing (if required, configurating)  the prerequisites on OCP like, Openshift Cert Manager, NFD Operator, Nvidia Operator.  
- [ ] https://github.com/openshift/instaslice-operator/issues/291 

/cc @rphillips

**Comment by kannon92** [comment]
I'd probably add https://github.com/openshift/instaslice-operator/issues/291 to this as this could bite us shortly after we release DP.

**Comment by rphillips** [comment]
We need to add CVE mitigation as well for the images.

**Comment by cpmeadors** [comment]
> I'd probably add #291 to this as this could bite us shortly after we release DP.

ocp version of bundle uses registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9

**Comment by kannon92** [comment]
@cpmeadors where can I find that?

**Comment by harche** [comment]
> I'd probably add #291 to this as this could bite us shortly after we release DP.

Thanks, added.

**Comment by harche** [comment]
> We need to add CVE mitigation as well for the images.

https://issues.redhat.com/browse/OCPNODE-2418

**Comment by rphillips** [comment]
add an olm dependency for cert-manager. The docs on how to do it are [here](https://olm.operatorframework.io/docs/concepts/olm-architecture/dependency-resolution/#m-docsconceptsolm-architectureoperator-catalogcreating-an-update-graph).

**Comment by rphillips** [comment]
Add dependencies: nfd, nvidia-gpu operator

**Comment by rphillips** [comment]
/close 

tracking this https://issues.redhat.com/browse/OCPNODE-2416
