### ISSUE TITLE
Define and use a prefix for InstaSlice-managed resources.

### ISSUE THREAD

**Issue by empovit** [openshift/instaslice-operator#33]
We need a prefix to unambiguously identify InstaSlice-managed resources, such as the total accelerator memory.

Example: `instaslice.redhat.com/accelerator-memory`.

We should avoid using HW vendor-specific prefixes to prevent confusion and trademark infringement. A vendor might also use a similar name in the future, creating a naming conflict. In addition, we probably want to be vendor-agnostic, e.g. `accelerator-memory` can represent GPU memory by multiple vendors.

**Comment by mamy-CS** [comment]
Related - https://github.com/openshift/instaslice-operator/issues/124

**Comment by mamy-CS** [comment]
Previous resource name - [nvidia.com/accelerator-memory]
New resource name representing quota - [instaslice.redhat.com/accelerator-memory-quota]

**Comment by asm582** [comment]
This issue has been resolved.
