### ISSUE TITLE
InstaSlice CR namespace

### ISSUE THREAD

**Issue by asm582** [openshift/instaslice-operator#48]
We need to agree on the InstaSlice CR namespace and add the correct RBACs to the InstaSlice CR hosting namespace, it has MIG slice placement information which apart from role admin, a regular user should not have access.

**Comment by asm582** [comment]
@harche @empovit any thoughts?

**Comment by empovit** [comment]
As the operator is part of the OpenShift org, I think we could use something like `openshift-accelerator-slicer` by default, similarly to `openshift-nfd` or `openshift-kmm`.

Also, IMO it should be customizable (including RBAC), to allow deployment into any namespace.

**Comment by asm582** [comment]
Closing this issue has the CR has been moved to namespace instaslice-system and we do not have prepared section in the CR
