### ISSUE TITLE
Add unit test for daemonset

### ISSUE THREAD

**Issue by asm582** [openshift/instaslice-operator#61]
create unit tests for daemonset that will run on GPU-enabled cluster, and run locally to verify the output

**Comment by asm582** [comment]
I agree, I think until we can "truly" mock a GPU this could be an approach.

**Comment by asm582** [comment]
@sairameshv  @mamy-CS  PR #67 shows a possible path, based on it I think more tests could be added.

**Comment by sairameshv** [comment]
I'm working on it @kannon92
