### ISSUE TITLE
Run instaslice on MAC

### ISSUE THREAD

**Issue by asm582** [openshift/instaslice-operator#71]
build and run Instaslice in emulator mode on a MacBook and test placement feature

**Comment by tardieu** [comment]
To build and push multi-arch images on mac run the following using your preferred container registry/repository:
```sh
docker buildx create --name project-v3-builder
docker buildx use project-v3-builder
IMG=quay.io/tardieu/instaslicev2-controller IMG_DMST=quay.io/tardieu/instaslicev2-daemonset make docker-buildx
```

**Comment by asm582** [comment]
@empovit How can we add this to our docs?

**Comment by empovit** [comment]
We have a Make target and a section in the docs for building multi-arch/cross-arch images. I tested it with both Podman and Docker. @tardieu are you saying it doesn't work on Mac?

**Comment by tardieu** [comment]
@empovit I have no problems running in emulator mode on mac. I did not open this bug and I don't know what was the issue for @asm582. He asked me to add instructions about multi-arch images here for now. I agree these belong somewhere in our doc. Could you add a blurb where you think this is appropriate? @asm582 you should close this issue if the problem has been resolved on your end.

**Comment by empovit** [comment]
Well, the thing is it _is_ mentioned in the documentation https://github.com/openshift/instaslice-operator/blob/main/README.md?plain=1#L166
> Cross-platform or multi-arch images can be built and pushed using make docker-buildx. When using Docker as your container tool, make sure to create a builder instance. Refer to [Multi-platform images](https://docs.docker.com/build/building/multi-platform/) for documentation on building mutli-platform images with Docker. You can change the destination platform(s) by setting PLATFORMS, e.g.:
>
> ```console
> PLATFORMS=linux/arm64,linux/amd64 make docker-buildx
> ```
