### ISSUE TITLE
Migration to operator-sdk

### ISSUE THREAD

**Issue by mamy-CS** [openshift/instaslice-operator#8]
Design Migration Doc - https://docs.google.com/document/d/1wpNMog34bhDUDeEMDrKCZhMHysQLMmsiQg3jOfACkRM/edit

**Comment by harche** [comment]
@mamy-CS feel free to close this if it is already done. Thanks.

**Comment by asm582** [comment]
@mamy-CS Do we know the status of this issue?

**Comment by mamy-CS** [comment]
Taken care of here - https://github.com/openshift/instaslice-operator/pull/32
The only thing remaining is the deployment of the operator using SDK bundle, opening another issue for it.
