### ISSUE TITLE
Move InstaSlice finalizer injection from webhook to controller

### ISSUE THREAD

**Issue by tardieu** [openshift/instaslice-operator#87]
The InstaSlice webhook adds an InstaSlice finalizer to the pod. This requires the controller to remove the finalizer before the pod can be deleted even if InstaSlice never had to allocate a slice for the pod, as for instance when a kueued pod is deleted before being admitted. While #83 added support for kueued pods, it does not address the finalizer situation and a kueued pod deleted before admission remains stuck with the InstaSlice finalizer.

To fix the problem, we should move the finalizer injection to the controller, only adding a finalizer once the pod has no other scheduling gates and is about to be processed by InstaSlice. Alternatively, we could remove the finalizer upon deletion (leaving the injection in the webhook) but adding and removing unnecessary finalizers is not going to scale well once we try to kueue thousands of pods.

**Comment by asm582** [comment]
Solved by #91
